### ISSUE TITLE
How to solve this SyntaxError?

### ISSUE THREAD

**Issue by impotter** [DrelezTM/YouTubeDLWhatsAppBOT#1]
user@user:~/YouTubeDLWhatsAppBOT$ npm start

> youtubedlbot@1.0.0 start
> node .

/home/user/YouTubeDLWhatsAppBOT/node_modules/whatsapp-web.js/src/util/Injected.js:98
                m.default?.prototype?.proxyName ||
                          ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/user/YouTubeDLWhatsAppBOT/node_modules/whatsapp-web.js/src/Client.js:10:36)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

**Comment by DrelezTM** [comment]
uninstall whatsapp-web.js
```js
npm uninstall whatsapp-web.js
```
install whatsapp-web.js fix button
```js
npm i github:pedroslopez/whatsapp-web.js#fix-buttons-list
```
